CREATE DATABASE budb;

# ADMIN ACCESS TABLE LIST
# ENSURE THAT ATLEAST ONE ADMIN STAYS IN THIS.
CREATE TABLE SOM_ADMIN (
	USERNAME VARCHAR(75) PRIMARY KEY,
	PASSWORD VARCHAR(75) NOT NULL
);

# TABLE TO STORE A LIST OF EXPERTISE
# AN ID IS NOT CONSIDERED HERE EVEN THOUGH IT WILL BE REFERED
# BECAUSE IT WILL BE USED VERY INFREQUENTLY TO UPDATE THE INFORMATION
# AND ANOTHER LEVEL OF INDIRECTION WOULD SLOW DOWN ACCESS TO THE INFO
# TO BE DISPLAYED.
CREATE TABLE SOM_EXPERTISE (
	TAG VARCHAR(255) PRIMARY KEY #STORES THE TEXT OF THE TAG
)ENGINE=MyISAM CHARACTER SET=utf8;

#TABLE TO STORE DATA FOR STUDENTS
CREATE TABLE SOM_STUDENT (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT, #REFERS TO THE UNIQUE STUDENT ID
	NAME VARCHAR (999) NOT NULL, #REFERES TO THE NAME OF THE STUDENT
	DESCRIPTION VARCHAR(999) DEFAULT NULL, #REFERES TO A SHORT DESCRIPTION ABOUT THE STUDENT
	RESUME_URL TEXT DEFAULT NULL, #REFERES TO THE URL LINK TO ANY ONLINE RESUME
	STATUS SMALLINT DEFAULT 0 #0 - UNPUBLISHED, 1 - PUBLISHED
)ENGINE=MyISAM CHARACTER SET=utf8;

# TABLE TO STORE STUDENT'S EXPERTISE
# A STUDENT MAY HAVE MORE THAN ONE EXPERTISE
CREATE TABLE SOM_STUDENT_EXPERTISE (
	SID INTEGER,
	TAG VARCHAR(255),

	FOREIGN KEY(SID) REFERENCES SOM_STUDENT(ID),
	FOREIGN KEY(TAG) REFERENCES SOM_EXPERTISE(TAG),
	PRIMARY KEY(SID,TAG)
)ENGINE=MyISAM CHARACTER SET=utf8;

#TABLE TO STORE THE RESUME INFO FOR SEARCHING OPTION
CREATE TABLE SOM_RESUME_INFO (
	SID INTEGER,
	DATA TEXT,

	FOREIGN KEY(SID) REFERENCES SOM_STUDENT(ID),
	FULLTEXT(DATA)
)ENGINE=MyISAM CHARACTER SET=utf8;